language: rust

rust:
  - stable

env:
  # Test building release
  - TARGET=build/disk
  # Test building dev
  - TARGET=build/diskdev
  # Run tests
  - TARGET=check

addons:
  apt:
    packages:
      - build-essential
      - nasm

install:
  - rustup component add clippy-preview

script:
  - ./autogen.sh
  - ./configure --enable-fatal-warnings
  - make $TARGET
